default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  #pool: 5
  #socket: /var/run/mysqld/mysqld.sock
  #host: localhost
  #password:

development:
  <<: *default
  database: coding_development

test:
  <<: *default
  database: coding_test

production:
  <<: *default
  database: coding_production
  username: coding
  password: <%= ENV['CODING_DATABASE_PASSWORD'] %>
